CREATE TABLE wishes (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  price NUMERIC(10, 2) NOT NULL CHECK (price >= 0),
  bought BOOLEAN NOT NULL DEFAULT FALSE
);